// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALE9OCyNeB5x6-bquzbBa__8VC6KZvWnA',
    appId: '1:719387819313:web:6fec63cb380e9fac030410',
    messagingSenderId: '719387819313',
    projectId: 'job-finder-app-test',
    authDomain: 'job-finder-app-test.firebaseapp.com',
    storageBucket: 'job-finder-app-test.firebasestorage.app',
    measurementId: 'G-YNZ1NB64GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXvsTOKNSSOvMtTXurEyHACpRYI_rSWac',
    appId: '1:719387819313:android:cfd94f8274687e31030410',
    messagingSenderId: '719387819313',
    projectId: 'job-finder-app-test',
    storageBucket: 'job-finder-app-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNXLVGjp89BPpkVu_qbtMj1MTVSTwmi4',
    appId: '1:719387819313:ios:37028f2da1558695030410',
    messagingSenderId: '719387819313',
    projectId: 'job-finder-app-test',
    storageBucket: 'job-finder-app-test.firebasestorage.app',
    iosBundleId: 'com.example.freelanceAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFNXLVGjp89BPpkVu_qbtMj1MTVSTwmi4',
    appId: '1:719387819313:ios:37028f2da1558695030410',
    messagingSenderId: '719387819313',
    projectId: 'job-finder-app-test',
    storageBucket: 'job-finder-app-test.firebasestorage.app',
    iosBundleId: 'com.example.freelanceAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALE9OCyNeB5x6-bquzbBa__8VC6KZvWnA',
    appId: '1:719387819313:web:26d28971f127653c030410',
    messagingSenderId: '719387819313',
    projectId: 'job-finder-app-test',
    authDomain: 'job-finder-app-test.firebaseapp.com',
    storageBucket: 'job-finder-app-test.firebasestorage.app',
    measurementId: 'G-C84DZ7C2Z2',
  );

}